#!/usr/bin/env python
from __future__ import print_function

import rospy
import qb_state

if __name__ == '__main__':
    try:
        qb_state.start_manager()
    except rospy.ROSInterruptException:
        pass
