#!/usr/bin/env python3
from __future__ import print_function

import rospy
import qb_speech

if __name__ == '__main__':
    try:
        qb_speech.start_manager()
    except rospy.ROSInterruptException:
        pass
