# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mirobot_driver/wheel_control.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class wheel_control(genpy.Message):
  _md5sum = "7bf657bb437a3a998dcf9c0bf0cd51fa"
  _type = "mirobot_driver/wheel_control"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 dir_l
uint8 speed_l
uint8 dir_r
uint8 speed_r
"""
  __slots__ = ['dir_l','speed_l','dir_r','speed_r']
  _slot_types = ['uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       dir_l,speed_l,dir_r,speed_r

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(wheel_control, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.dir_l is None:
        self.dir_l = 0
      if self.speed_l is None:
        self.speed_l = 0
      if self.dir_r is None:
        self.dir_r = 0
      if self.speed_r is None:
        self.speed_r = 0
    else:
      self.dir_l = 0
      self.speed_l = 0
      self.dir_r = 0
      self.speed_r = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.dir_l, _x.speed_l, _x.dir_r, _x.speed_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.dir_l, _x.speed_l, _x.dir_r, _x.speed_r,) = _get_struct_4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.dir_l, _x.speed_l, _x.dir_r, _x.speed_r))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.dir_l, _x.speed_l, _x.dir_r, _x.speed_r,) = _get_struct_4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
