
obstacle_range: 2.5
raytrace_range: 3.5
footprint: [[-0.15, -0.25], [0.35, -0.25], [0.35, 0.25], [-0.15, 0.25]]
footprint_padding: 0.01
inflation_radius: 0.35
cost_scaling_factor: 0.5
map_type: costmap
transform_tolerance: 0.2
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}