local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 10
  publish_frequency: 10
  static_map: false
  rolling_window: true
  width: 3.5
  height: 3.5
  resolution: 0.02
  transform_tolerance: 1.0