// Generated by gencpp from file bot_hal/wheel_control.msg
// DO NOT EDIT!


#ifndef BOT_HAL_MESSAGE_WHEEL_CONTROL_H
#define BOT_HAL_MESSAGE_WHEEL_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bot_hal
{
template <class ContainerAllocator>
struct wheel_control_
{
  typedef wheel_control_<ContainerAllocator> Type;

  wheel_control_()
    : id(0)
    , speed(0)  {
    }
  wheel_control_(const ContainerAllocator& _alloc)
    : id(0)
    , speed(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef int32_t _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::bot_hal::wheel_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bot_hal::wheel_control_<ContainerAllocator> const> ConstPtr;

}; // struct wheel_control_

typedef ::bot_hal::wheel_control_<std::allocator<void> > wheel_control;

typedef boost::shared_ptr< ::bot_hal::wheel_control > wheel_controlPtr;
typedef boost::shared_ptr< ::bot_hal::wheel_control const> wheel_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bot_hal::wheel_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bot_hal::wheel_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bot_hal

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'bot_hal': ['/home/whoobee/mirobot/ros_ws/src/bot_hal/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bot_hal::wheel_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bot_hal::wheel_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bot_hal::wheel_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bot_hal::wheel_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot_hal::wheel_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bot_hal::wheel_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bot_hal::wheel_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6844aaf90d2570626588414c58ddac1a";
  }

  static const char* value(const ::bot_hal::wheel_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6844aaf90d257062ULL;
  static const uint64_t static_value2 = 0x6588414c58ddac1aULL;
};

template<class ContainerAllocator>
struct DataType< ::bot_hal::wheel_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bot_hal/wheel_control";
  }

  static const char* value(const ::bot_hal::wheel_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bot_hal::wheel_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"int32 speed\n"
;
  }

  static const char* value(const ::bot_hal::wheel_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bot_hal::wheel_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wheel_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bot_hal::wheel_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bot_hal::wheel_control_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOT_HAL_MESSAGE_WHEEL_CONTROL_H
