#!/usr/bin/env python
from __future__ import print_function

import rospy
import qb_waypoint_manager

if __name__ == '__main__':
    try:
        qb_waypoint_manager.start_manager()
    except rospy.ROSInterruptException:
        pass
