#!/usr/bin/env python
from __future__ import print_function

import rospy
import qb_docker

if __name__ == '__main__':
    try:
        qb_docker.start_manager()
    except rospy.ROSInterruptException:
        pass
