#!/usr/bin/env python
from __future__ import print_function

import rospy
import qb_alive

if __name__ == '__main__':
    try:
        qb_alive.start_manager()
    except rospy.ROSInterruptException:
        pass
