// Generated by gencpp from file mirobot_driver/wheel_control.msg
// DO NOT EDIT!


#ifndef MIROBOT_DRIVER_MESSAGE_WHEEL_CONTROL_H
#define MIROBOT_DRIVER_MESSAGE_WHEEL_CONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mirobot_driver
{
template <class ContainerAllocator>
struct wheel_control_
{
  typedef wheel_control_<ContainerAllocator> Type;

  wheel_control_()
    : dir_l(0)
    , speed_l(0)
    , dir_r(0)
    , speed_r(0)  {
    }
  wheel_control_(const ContainerAllocator& _alloc)
    : dir_l(0)
    , speed_l(0)
    , dir_r(0)
    , speed_r(0)  {
  (void)_alloc;
    }



   typedef uint8_t _dir_l_type;
  _dir_l_type dir_l;

   typedef uint8_t _speed_l_type;
  _speed_l_type speed_l;

   typedef uint8_t _dir_r_type;
  _dir_r_type dir_r;

   typedef uint8_t _speed_r_type;
  _speed_r_type speed_r;





  typedef boost::shared_ptr< ::mirobot_driver::wheel_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mirobot_driver::wheel_control_<ContainerAllocator> const> ConstPtr;

}; // struct wheel_control_

typedef ::mirobot_driver::wheel_control_<std::allocator<void> > wheel_control;

typedef boost::shared_ptr< ::mirobot_driver::wheel_control > wheel_controlPtr;
typedef boost::shared_ptr< ::mirobot_driver::wheel_control const> wheel_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mirobot_driver::wheel_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mirobot_driver::wheel_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mirobot_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'mirobot_driver': ['/home/whoobee/mirobot/ros_ws/src/mirobot_driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mirobot_driver::wheel_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mirobot_driver::wheel_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirobot_driver::wheel_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mirobot_driver::wheel_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirobot_driver::wheel_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mirobot_driver::wheel_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mirobot_driver::wheel_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7bf657bb437a3a998dcf9c0bf0cd51fa";
  }

  static const char* value(const ::mirobot_driver::wheel_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7bf657bb437a3a99ULL;
  static const uint64_t static_value2 = 0x8dcf9c0bf0cd51faULL;
};

template<class ContainerAllocator>
struct DataType< ::mirobot_driver::wheel_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mirobot_driver/wheel_control";
  }

  static const char* value(const ::mirobot_driver::wheel_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mirobot_driver::wheel_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 dir_l\n"
"uint8 speed_l\n"
"uint8 dir_r\n"
"uint8 speed_r\n"
;
  }

  static const char* value(const ::mirobot_driver::wheel_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mirobot_driver::wheel_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dir_l);
      stream.next(m.speed_l);
      stream.next(m.dir_r);
      stream.next(m.speed_r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wheel_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mirobot_driver::wheel_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mirobot_driver::wheel_control_<ContainerAllocator>& v)
  {
    s << indent << "dir_l: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dir_l);
    s << indent << "speed_l: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.speed_l);
    s << indent << "dir_r: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dir_r);
    s << indent << "speed_r: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.speed_r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIROBOT_DRIVER_MESSAGE_WHEEL_CONTROL_H
